version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      javascript-dependencies:
        patterns: ['*']
  - package-ecosystem: uv
    directory: /apps/vision-engine
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
